cleanup svc-managers
kavyamani596/ODIM pull request #10
Opened 2023-02-16 04:26 UTC by kavyamani596

2023-02-20 05:14 UTC, chauberahul1993 approved these changes

2023-02-20 08:48 UTC, mohamed-shahid-afrid approved these changes

2023-02-24 07:01 UTC, amar-shalgar requested changes

2023-02-24 07:01 UTC, amar-shalgar commented on svc-update/update/common.go
> +		l.Log.Debugf("monitor task data payload: %s", string(monitorTaskData.respBody))
This needs logfields

2023-02-24 07:01 UTC, amar-shalgar commented on svc-update/update/simpleUpdate.go
> +	l.Log.Debugf("payload to plugin : %s", updateRequestBody)
Log fields are missing

2023-02-24 07:01 UTC, amar-shalgar commented on svc-update/update/simpleUpdate.go
> +	l.Log.Debugf("updated payload to plugin : %s", updateRequestBody)
log fields missing

2023-02-24 07:01 UTC, amar-shalgar commented on svc-update/update/startUpdate.go
> +	l.Log.Debugf("updated payload to plugin : %s", updateRequestBody)
log fields missing, check cross

2023-03-07 05:46 UTC, amar-shalgar requested changes

2023-03-07 05:46 UTC, amar-shalgar commented on svc-update/umodel/update.go
> +	l.Log.Debug("all keys from database:", keysArray)
fields missing

2023-03-07 05:51 UTC, amar-shalgar approved these changes

2023-03-07 05:51 UTC, merged