Cleanup logs and add debug logs in aggregation service
kavyamani596/ODIM pull request #13
Opened 2023-03-06 05:54 UTC by kavyamani596

2023-03-08 11:50 UTC, arahimanshaik approved these changes

2023-03-08 12:15 UTC, mohamed-shahid-afrid approved these changes

2023-03-08 12:31 UTC, amar-shalgar requested changes

2023-03-08 12:31 UTC, amar-shalgar commented on svc-aggregation/main.go
> +const (
action id and name should be in constant under lib directories

2023-03-08 12:31 UTC, amar-shalgar commented on svc-aggregation/main.go
> +	aggCtx := agcommon.CreateContext(aggTransactionID.String(), aggActionID, aggActionName, "1", common.AggregationService, podName)
what exactly is "1" here?

2023-03-08 12:35 UTC, kavyamani596 commented on svc-aggregation/main.go
> +	aggCtx := agcommon.CreateContext(aggTransactionID.String(), aggActionID, aggActionName, "1", common.AggregationService, podName)
this is the thread ID

2023-03-08 12:57 UTC, amar-shalgar requested changes

2023-03-08 12:57 UTC, amar-shalgar commented on lib-utilities/common/constants.go
> +	// Aggregation service Action ID
Look at the previous implementation for action id and name

2023-03-10 10:07 UTC, amar-shalgar approved these changes

2023-03-10 10:07 UTC, merged